FROM python:3.8

RUN python -m pip install\
 torch==1.10.2+cpu \
 torchvision==0.11.3+cpu \
 torchaudio==0.10.2+cpu \
 -f https://download.pytorch.org/whl/cpu/torch_stable.html

RUN python -m pip install opacus

COPY . .

RUN python download_dataset.py
